"""Stable Manual Review reason codes used by reporting decisions."""

from __future__ import annotations

PRODUCT_COUNT_MISMATCH = "PRODUCT_COUNT_MISMATCH"
PRODUCT_AMOUNT_RECONCILIATION_FAILED = "PRODUCT_AMOUNT_RECONCILIATION_FAILED"
INCOMPLETE_PROMOTION_EVIDENCE = "INCOMPLETE_PROMOTION_EVIDENCE"
NO_VALID_PRODUCTS = "NO_VALID_PRODUCTS"
INCOME_COMPLETION_ANCHOR_MISSING = "INCOME_COMPLETION_ANCHOR_MISSING"

PRODUCT_SUMMARY_EXCLUSION_REASON_CODES = frozenset(
    {
        PRODUCT_COUNT_MISMATCH,
        PRODUCT_AMOUNT_RECONCILIATION_FAILED,
        INCOMPLETE_PROMOTION_EVIDENCE,
        NO_VALID_PRODUCTS,
    }
)
